# Generated by Django 5.2.3 on 2026-03-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Optional', max_length=50, null=True, unique=True, verbose_name='username'),
        ),
    ]
