# Generated by Django 5.2.3 on 2026-03-08 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('starnest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contribution',
            name='user_savings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starnest.usersavings'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='user_savings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starnest.usersavings'),
        ),
    ]
