# Generated by Django 5.2.3 on 2026-03-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starnest', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingplan',
            name='benefits',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
