# Generated by Django 5.2.3 on 2026-03-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starnest', '0003_savingplan_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingplan',
            name='video_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
