# Generated by Django 5.2.3 on 2026-03-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starnest', '0004_savingplan_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingplan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
