# Generated by Django 5.2.3 on 2026-03-12 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starnest', '0005_alter_savingplan_interest_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ref', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('user_savings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starnest.usersavings')),
            ],
        ),
        migrations.DeleteModel(
            name='Contribution',
        ),
    ]
