# Generated by Django 5.2.3 on 2026-03-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starnest', '0006_deposit_delete_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavings',
            name='completed_clearance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
