# Generated by Django 5.2.3 on 2026-03-17 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starnest', '0007_usersavings_completed_clearance_alter_deposit_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ref', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'withdrawal')], default='deposit', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_savings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starnest.usersavings')),
            ],
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
    ]
