# Generated by Django 5.2.3 on 2026-03-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starnest', '0008_transaction_delete_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingplan',
            name='image',
            field=models.ImageField(blank=True, default='plan.jpg', null=True, upload_to='plans'),
        ),
        migrations.AddField(
            model_name='usersavings',
            name='hands',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
