# Generated by Django 5.2.3 on 2026-03-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starnest', '0009_savingplan_image_usersavings_hands'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
