# Generated by Django 5.2.3 on 2026-04-03 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starnest', '0011_transaction_user_alter_usersavings_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Withdrawal',
        ),
    ]
